server {
    listen 80;
    server_name robinjallade.com;

    root /usr/share/nginx/html;
    index index.html;

    # Supprimer l'extension .html
    location / {
        try_files $uri $uri.html $uri/ =404;
    }
}
