server {
    listen 80;
    server_name robinjallade.com;

    root /usr/share/nginx/html; # Chemin vers vos fichiers statiques
    index index.html;

    # Supprimer les extensions .html des URL
    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    # Assurez-vous que /index.html redirige vers /index sans extension
    location = /index {
        rewrite ^ /index.html;
    }

    # Redirection 404 personnalisée (facultatif)
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
